// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCuNzho061GKfHybM2g1iMwOF6AEDKbGs',
    appId: '1:226005137950:web:a77e24b169c238c9248c0f',
    messagingSenderId: '226005137950',
    projectId: 'chat-app-5eae6',
    authDomain: 'chat-app-5eae6.firebaseapp.com',
    storageBucket: 'chat-app-5eae6.appspot.com',
    measurementId: 'G-27782J3HSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDptR1zBWGUcLXARe2RzYTBGSuo_2HNtxs',
    appId: '1:226005137950:android:36e0c00f3f97ba6d248c0f',
    messagingSenderId: '226005137950',
    projectId: 'chat-app-5eae6',
    storageBucket: 'chat-app-5eae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvpKxp8orD-Y6KbAs2zppotx7mPFv_E6k',
    appId: '1:226005137950:ios:b785a8cc873a4b2a248c0f',
    messagingSenderId: '226005137950',
    projectId: 'chat-app-5eae6',
    storageBucket: 'chat-app-5eae6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
